/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.una.proyecto1.view;

import java.io.File;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import com.una.proyecto1.controller.ControladorPrestamo;
import com.una.proyecto1.model.logica.prestamo.Mensualidad;
import com.una.proyecto1.model.logica.prestamo.Prestamo;
import com.una.proyecto1.view.componentes.MensualidadTableModel;

import static javax.swing.JOptionPane.showMessageDialog;

public class PrestamoClientes extends javax.swing.JFrame {
    private int cedula = 0;

    /**
     * Creates new form PrestamoClientes
     * 
     * 
     * 
     * @param cedula cedula del cliente
     */
    public PrestamoClientes(int cedula) {
        this.cedula = cedula;
        initComponents();
        init();
    }

    void init() {
        if (ControladorPrestamo.getInstancia().recuperarCliente(cedula) == null) {
            throw new RuntimeException("El cliente no existe");
        }
        this.setTitle(String.format("Prestamos del cliente %d", cedula));
        recargarPrestamos();
    }

    void recargarPrestamos() {
        cmbPrestamo.removeAllItems();
        cmbPrestamo.addItem("Nuevo Prestamo");
        prestamos = ControladorPrestamo.getInstancia().recuperarPrestamos(cedula);

        for (Integer i = 0; i < prestamos.size(); i++) {
            cmbPrestamo.addItem("Prestamo #" + (i + 1));
        }
    }

    void recargarMensualidades() {
        Integer indice = cmbPrestamo.getSelectedIndex();
        if (indice != 0) {
            List<Mensualidad> mensualidades = ControladorPrestamo.getInstancia().recuperarMensualidades(cedula,
                    indice - 1);
            tablaMensualidad.setModel(new MensualidadTableModel(mensualidades));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMensualidad = new javax.swing.JTable();
        cmbPrestamo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMensualidad = new javax.swing.JFormattedTextField();
        btnAgregarMensualidad = new javax.swing.JToggleButton();
        btnNuevoPrestamo = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        txtPlazo = new javax.swing.JTextField();
        txtTasa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemReportePrestamos = new javax.swing.JMenuItem();
        menuItemReportePagos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaMensualidad.setModel(new MensualidadTableModel());
        jScrollPane1.setViewportView(tablaMensualidad);

        cmbPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo Prestamo" }));

        jLabel1.setText("Prestamo");

        jLabel3.setText("Monto:");

        jLabel4.setText("Plazo:");

        jLabel5.setText("tasa:");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Mensualidad:");

        txtMensualidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnAgregarMensualidad.setText("Agregar");
        btnAgregarMensualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMensualidadActionPerformed(evt);
            }
        });

        btnNuevoPrestamo.setText("Nuevo ");
        btnNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrestamoActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        menuItemReportePrestamos.setText("Reporte prestamos");
        menuItemReportePrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReportePrestamosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemReportePrestamos);

        menuItemReportePagos.setText("Pagos de prestamo");
        menuItemReportePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReportePagosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemReportePagos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1).addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbPrestamo, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(txtPlazo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3).addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTasa).addComponent(txtMonto,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnNuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 87,
                                                Short.MAX_VALUE)
                                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 1,
                                                Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 273,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregarMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1).addComponent(jLabel3)
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4).addComponent(jLabel5).addComponent(btnNuevoPrestamo)
                                .addComponent(txtPlazo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAgregarMensualidad, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemReportePrestamosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuItemReportePrestamosActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogo = new JFileChooser();
        if (dialogo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = dialogo.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            if (!ruta.endsWith(".pdf")) {
                ruta = ruta + ".pdf";
            }
            boolean resultado = ControladorPrestamo.getInstancia().generarReportePrestamos(ruta, cedula);
            if (resultado) {
                JOptionPane.showMessageDialog(this, "Reporte guardado en la ruta: " + ruta, "Generado reporte",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "verifique que se puede acceder al archivo",
                        "Error al generar el PDF", JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_menuItemReportePrestamosActionPerformed

    private void menuItemReportePagosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuItemReportePagosActionPerformed
        // TODO add your handling code here:
        if (cmbPrestamo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un prestamo en el formulario", "Cancelada operacion",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser dialogo = new JFileChooser();
        if (dialogo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = dialogo.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            if (!ruta.endsWith(".pdf")) {
                ruta = ruta + ".pdf";
            }
            boolean resultado = ControladorPrestamo.getInstancia().generarReportePagos(ruta, cedula,
                    cmbPrestamo.getSelectedIndex() - 1);
            if (resultado) {
                JOptionPane.showMessageDialog(this, "Reporte guardado en la ruta: " + ruta, "Generado reporte",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "verifique que se puede acceder al archivo",
                        "Error al generar el PDF", JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_menuItemReportePagosActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSeleccionarActionPerformed
        Integer indice = cmbPrestamo.getSelectedIndex();
        if (indice != 0) {
            List<Prestamo> prestamos = ControladorPrestamo.getInstancia().recuperarPrestamos(cedula);
            Prestamo prestamo = prestamos.get(indice - 1);
            txtMonto.setText(Double.valueOf(prestamo.getMonto()).toString());
            txtPlazo.setText(Integer.valueOf(prestamo.getPlazo()).toString());
            txtTasa.setText(Double.valueOf(prestamo.getTasa()).toString());
        }
    }// GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAgregarMensualidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarMensualidadActionPerformed
        try {
            Integer indice = cmbPrestamo.getSelectedIndex();
            Double saldo = Double.valueOf(txtMensualidad.getText());
            if (indice != 0 && ControladorPrestamo.getInstancia().agregarMensualidad(cedula, indice - 1, saldo)) {
                recargarMensualidades();
            } else {
                showMessageDialog(null, "Ingrese una mensualidad valida");
            }
        } catch (Exception e) {
            showMessageDialog(null, "Ingrese un valor numerico correcto");
        }
    }// GEN-LAST:event_btnAgregarMensualidadActionPerformed

    private void btnNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevoPrestamoActionPerformed
        try {
            ControladorPrestamo.getInstancia().agregarPrestamo(cedula, Double.parseDouble(txtMonto.getText()),
                    Integer.valueOf(txtPlazo.getText()), Double.parseDouble(txtTasa.getText()));
            recargarPrestamos();
        } catch (Exception e) {
            showMessageDialog(null, "Ingrese valores validos");
        }

    }// GEN-LAST:event_btnNuevoPrestamoActionPerformed

    List<Prestamo> prestamos;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarMensualidad;
    private javax.swing.JButton btnNuevoPrestamo;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cmbPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItemReportePagos;
    private javax.swing.JMenuItem menuItemReportePrestamos;
    private javax.swing.JTable tablaMensualidad;
    private javax.swing.JFormattedTextField txtMensualidad;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPlazo;
    private javax.swing.JTextField txtTasa;
    // End of variables declaration//GEN-END:variables
}
